image: tiagofgh/my-sfdx-delta-cli:latest

definitions:
  caches:
    sfplugins: ~/.local/share/sf/plugins

pipelines:
  pull-requests:
    "**":
      - step:
          name: "INT con cache de plugins"
          caches:
            - sfplugins
          script:
            - echo "$AUTH_URL_INT" > authurl
            - sf org login sfdx-url -f authurl -s --alias ORG-TEST
            - sf plugins install sfdx-git-delta || true
            - git fetch --all --prune
            - sfdx sgd:source:delta \
                --to "origin/$BITBUCKET_BRANCH" \
                --from "origin/$BITBUCKET_PR_DESTINATION_BRANCH" \
                --output "." --generate-delta
            - if [ -f manifest/package.xml ]; then
                sf project deploy validate --manifest manifest/package.xml \
                  --target-org ORG-TEST --wait 10 --test-level ${TESTLEVEL:-RunLocalTests} --verbose;
              else
                echo "No hay cambios";
              fi