name: Deploy QA

on:
  workflow_dispatch:
  push:
    branches: [ "qa" ]

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    container:
      image: docker://tiagofgh/my-sfdx-delta-cli:latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Auth QA
        env: { AUTH_URL_QA: ${{ secrets.AUTH_URL_QA }} }
        run: |
          echo "$AUTH_URL_QA" > authurl
          sf org login sfdx-url -f authurl -s --alias ORG-QA

      - name: Delta (main → qa)
        run: |
          git fetch --depth=0 origin
          sfdx sgd:source:delta --to "HEAD" --from "origin/main" --output "." --generate-delta
          if [ ! -f manifest/package.xml ]; then
            echo "No hay cambios para desplegar a QA."
            exit 0
          fi

      - name: Deploy to QA
        env: { TESTLEVEL: ${{ secrets.TESTLEVEL || 'RunLocalTests' }} }
        run: |
          sf project deploy start \
            --manifest manifest/package.xml \
            --target-org ORG-QA \
            --wait 10 \
            --test-level "$TESTLEVEL" \
            --verbose