jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: docker://tiagofgh/my-sfdx-delta-cli:v1.0.9
    steps:
      - name: Checkout INT
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Fix Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: SF version & plugins (debug)
        run: |
          sf --version
          sf plugins
          sf help sgd:source:delta | head -n 5 || true

      - name: Ensure sfdx-git-delta present (self-heal)
        run: |
          if ! sf plugins | grep -qi 'sfdx-git-delta'; then
            echo "sfdx-git-delta missing -> installing..."
            sf plugins install sfdx-git-delta --force
            sf plugins
            sf help sgd:source:delta | head -n 5 || true
          else
            echo "sfdx-git-delta present."
          fi
