## Validate INT  

name: Validate INT

on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: docker://tiagofgh/my-sfdx-delta-cli:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Auth INT
        env: { AUTH_URL_INT: ${{ secrets.AUTH_URL_INT }} }
        run: |
          echo "$AUTH_URL_INT" > authurl
          sf org login sfdx-url -f authurl -s --alias ORG-TEST
          sf org display --target-org ORG-TEST

      - name: Delta (PR base vs head)
        run: |
          git fetch --depth=0 origin
          BASE="${{ github.base_ref || 'main' }}"
          HEAD="${{ github.head_ref || github.ref_name }}"
          echo "Delta FROM=$BASE TO=$HEAD"
          sfdx sgd:source:delta --to "origin/$HEAD" --from "origin/$BASE" --output "." --generate-delta
          if [ ! -f manifest/package.xml ]; then
            echo "No hay cambios para validar."
            exit 0
          fi
          sed -n '1,120p' manifest/package.xml || true

      - name: Validate in INT
        env: { TESTLEVEL: ${{ secrets.TESTLEVEL || 'RunLocalTests' }} }
        run: |
          sf project deploy validate \
            --manifest manifest/package.xml \
            --target-org ORG-TEST \
            --wait 10 \
            --test-level "$TESTLEVEL" \
            --verbose
