name: Validate INT

on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: docker://tiagofgh/my-sfdx-delta-cli:latest   # o tu tag v1.0.x que sí exista

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: SF version (debug)
        run: sf --version

      # Airbag: instala el plugin si no está (amd64) y valida el comando
      - name: Ensure sfdx-git-delta is present
        run: |
          set -e
          sf plugins || true

          if ! sf help sgd:source:delta >/dev/null 2>&1; then
            echo "Installing sfdx-git-delta…"
            # intenta vía sf; si no, fallback a npm global
            yes | sf plugins install sfdx-git-delta --force || npm install -g sfdx-git-delta
          fi

          echo "Verifying plugin…"
          sf help sgd:source:delta >/dev/null 2>&1
          sf plugins

      - name: Auth INT
        env:
          AUTH_URL_INT: ${{ secrets.AUTH_URL_INT }}
        run: |
          echo "$AUTH_URL_INT" > authurl
          sf org login sfdx-url -f authurl -s --alias ORG-TEST
          sf org display --target-org ORG-TEST

      - name: Delta (PR base vs head)
        run: |
          set -e
          git fetch --all --prune
          BASE="${{ github.base_ref || 'main' }}"
          HEAD="${{ github.head_ref || github.ref_name }}"
          echo "Delta FROM=$BASE TO=$HEAD"

          # Sintaxis correcta (con DOS PUNTOS)
          sf sgd:source:delta \
            --to "origin/$HEAD" \
            --from "origin/$BASE" \
            --output "." \
            --generate-delta

          if [ ! -f manifest/package.xml ]; then
            echo "No hay cambios para validar en INT."
            exit 0
          fi
          head -n 100 manifest/package.xml || true

      - name: Validate in INT
        env:
          TESTLEVEL: ${{ secrets.TESTLEVEL || 'RunLocalTests' }}
        run: |
          sf project deploy validate \
            --manifest manifest/package.xml \
            --target-org ORG-TEST \
            --wait 10 \
            --test-level "$TESTLEVEL" \
            --verbose
