name: Validate INT

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Validate INT workflow is alive"
        